### ISSUE TITLE
Error Training VOCOS (UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte)

### ISSUE THREAD

**Issue by SeamusMullan** [charactr-platform/vocos#17]
I've been trying to train my own model with VOCOS using Google Colab but came across the following error when I ran the train.py file

``'utf-8' codec can't decode byte 0xff in position 0: invalid start byte```

The Full log is below but as far as I know I have everything configured right according to the README.md. I'm a bit new to Audio Synthesis so any help is great!

Full Log:

```
Global seed set to 4444
Trainer already configured with model summary callbacks: [<class 'pytorch_lightning.callbacks.model_summary.ModelSummary'>]. Skipping setting a default `ModelSummary` callback.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
[rank: 0] Global seed set to 4444
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2023-07-09 17:26:37.331298: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

   | Name                           | Type                         | Params
---------------------------------------------------------------------------------
0  | feature_extractor              | MelSpectrogramFeatures       | 0     
1  | feature_extractor.mel_spec     | MelSpectrogram               | 0     
2  | backbone                       | VocosBackbone                | 13.0 M
3  | backbone.embed                 | Conv1d                       | 358 K 
4  | backbone.norm                  | LayerNorm                    | 1.0 K 
5  | backbone.convnext              | ModuleList                   | 12.6 M
6  | backbone.final_layer_norm      | LayerNorm                    | 1.0 K 
7  | head                           | ISTFTHead                    | 526 K 
8  | head.out                       | Linear                       | 526 K 
9  | head.istft                     | ISTFT                        | 0     
10 | multiperioddisc                | MultiPeriodDiscriminator     | 41.1 M
11 | multiperioddisc.discriminators | ModuleList                   | 41.1 M
12 | multiresddisc                  | MultiResolutionDiscriminator | 600 K 
13 | multiresddisc.discriminators   | ModuleList                   | 600 K 
14 | disc_loss                      | DiscriminatorLoss            | 0     
15 | gen_loss                       | GeneratorLoss                | 0     
16 | feat_matching_loss             | FeatureMatchingLoss          | 0     
17 | melspec_loss                   | MelSpecReconstructionLoss    | 0     
18 | melspec_loss.mel_spec          | MelSpectrogram               | 0     
---------------------------------------------------------------------------------
55.2 M    Trainable params
0         Non-trainable params
55.2 M    Total params
220.950   Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/content/drive/MyDrive/Colab Notebooks/train.py", line 9, in <module>
    cli.trainer.fit(model=cli.model, datamodule=cli.datamodule)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 603, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1098, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1177, in _run_stage
    self._run_train()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1190, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1255, in _run_sanity_check
    val_loop._reload_evaluation_dataloaders()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 234, in _reload_evaluation_dataloaders
    self.trainer.reset_val_dataloader()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 1635, in reset_val_dataloader
    self.num_val_batches, self.val_dataloaders = self._data_connector._reset_eval_dataloader(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 357, in _reset_eval_dataloader
    dataloaders = self._request_dataloader(mode)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 446, in _request_dataloader
    dataloader = source.dataloader()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 524, in dataloader
    return method()
  File "/usr/local/lib/python3.10/dist-packages/vocos/dataset.py", line 38, in val_dataloader
    return self._get_dataloder(self.val_config, train=False)
  File "/usr/local/lib/python3.10/dist-packages/vocos/dataset.py", line 28, in _get_dataloder
    dataset = VocosDataset(cfg, train=train)
  File "/usr/local/lib/python3.10/dist-packages/vocos/dataset.py", line 44, in __init__
    self.filelist = f.read().splitlines()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by SeamusMullan** [comment]
Fix:
use a software like Notepad++ to change the encoding type of the training and validation files
( Encoding -> utf-8 )
